# Generated by Django 5.2.8 on 2026-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_token', models.CharField(help_text='Get it from https://railway.com/account/tokens', max_length=255, verbose_name='Railway Token')),
                ('project_name', models.CharField(default='Live Stream', help_text='Use a unique name for your project', max_length=255, verbose_name='Project Name')),
                ('docker_image', models.CharField(default='imvickykumar999/stream-downloader', help_text='Docker image to deploy (e.g., imvickykumar999/stream-downloader)', max_length=255, verbose_name='Docker Image')),
                ('stream_key', models.CharField(blank=True, help_text='Get it from https://studio.youtube.com/channel/UC/livestreaming', max_length=255, null=True, verbose_name='Stream Key')),
                ('youtube_id', models.CharField(blank=True, help_text='YouTube video ID (e.g., 4UTdZpN26Bs from https://www.youtube.com/watch?v=4UTdZpN26Bs)', max_length=50, null=True, verbose_name='YouTube ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active configuration')),
            ],
            options={
                'verbose_name': 'Railway Deployment',
                'verbose_name_plural': 'Railway Deployments',
                'ordering': ['-created_at'],
            },
        ),
    ]
