# Generated by Django 5.2.8 on 2026-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaydeployment',
            name='railway_project_id',
            field=models.CharField(blank=True, help_text='Railway project ID (set after first deployment)', max_length=255, null=True, verbose_name='Railway Project ID'),
        ),
        migrations.AddField(
            model_name='railwaydeployment',
            name='railway_service_id',
            field=models.CharField(blank=True, help_text='Railway service ID (set after first deployment)', max_length=255, null=True, verbose_name='Railway Service ID'),
        ),
    ]
