# Generated by Django 5.2.8 on 2026-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_railwaydeployment_railway_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaydeployment',
            name='stream_key',
            field=models.CharField(default='', help_text='Get it from https://studio.youtube.com/channel/UC/livestreaming', max_length=255, verbose_name='Stream Key'),
        ),
        migrations.AlterField(
            model_name='railwaydeployment',
            name='youtube_id',
            field=models.CharField(default='', help_text='YouTube video ID (e.g., 4UTdZpN26Bs from https://www.youtube.com/watch?v=4UTdZpN26Bs)', max_length=50, verbose_name='YouTube ID'),
        ),
    ]
